#!/usr/bin/env ruby

Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x --force gemmyrb`
puts `gem build gemmy.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
